apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: cnpg-postgresql
  namespace: kubocd-system
spec:
  description: PostgreSQL server (CNPG), one Connection per logical database
  package:
    repository: quay.io/okdp/sandbox-dependencies/cnpg-postgresql
    tag: 18.3-p03
    interval: 30m
    timeout: 10m
  parameters:
    databases:
      - name: keycloak
        owner: { username: keycloak, passwordSecret: creds-keycloak-db }
  targetNamespace: cnpg-system
  createNamespace: true
