apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: external-secrets
  namespace: kubocd-system
spec:
  description: External Secrets Operator, the CRDs the Control Plane's secret screens rest on
  package:
    repository: quay.io/okdp/sandbox-dependencies/external-secrets
    tag: 0.15.1-p03
    interval: 30m
    timeout: 10m
  targetNamespace: external-secrets
  createNamespace: true
