apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: local-secrets-provider
  namespace: kubocd-system
spec:
  description: Local secrets stand-in (the secret list simulates a secret manager)
  package:
    repository: quay.io/kubotal/sandbox-dependencies/local-secrets-provider
    tag: 1.0.0-p06
    interval: 30m
    timeout: 10m
  parameters:
    secrets:
      - name: creds-keycloak-db
        data:
          username: "keycloak"
          password: "keycloak123"
