apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: spark-rbac
  namespace: kubocd-system
spec:
  description: "Spark ServiceAccount and RBAC for Spark applications"
  package:
    repository: quay.io/kubotal/platform-packages/spark-rbac
    tag: 1.0.1-cnx02
  targetNamespace: default
  createNamespace: false
